services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_MEMORY_LIMIT', '256M');
        define('WP_MAX_MEMORY_LIMIT', '256M');
        define('FORCE_SSL_ADMIN', true);
        define('DISALLOW_FILE_EDIT', true);
        define('AUTOMATIC_UPDATER_DISABLED', false);
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}

    volumes:
      - wp_html:/var/www/html

    labels:
      - traefik.enable=true
      - traefik.http.routers.${SERVICE_NAME}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure
      - traefik.http.routers.${SERVICE_NAME}.tls=true
      - traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=80

  wpcli:
    build:
      context: .
      dockerfile: Dockerfile.wpcli
    user: "33:33"
    working_dir: /var/www/html
    command: ["/scripts/bootstrap.sh"]
    restart: "no"

    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      HOME: /tmp
      DOMAIN: ${DOMAIN}
      WP_TITLE: ${WP_TITLE}
      STUDENT_CODE: ${STUDENT_CODE}
      STUDENT_NAME: ${STUDENT_NAME}
      STUDENT_SURNAME: ${STUDENT_SURNAME}
      STUDENT_EMAIL: ${STUDENT_EMAIL}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      ELEMENTOR_PRO_URL: ${ELEMENTOR_PRO_URL}
      ELEMENTOR_PRO_LICENSE: ${ELEMENTOR_PRO_LICENSE}
    volumes:
      - wp_html:/var/www/html

volumes:
  wp_html: