FROM wordpress:cli

USER root

COPY scripts/bootstrap.sh /scripts/bootstrap.sh
COPY mu-plugins/smtp.php /tmp/smtp.php
# COPY plugins/elementor-pro.zip /plugins/elementor-pro.zip

RUN chmod +x /scripts/bootstrap.sh \
    && chown 33:33 /scripts/bootstrap.sh /tmp/smtp.php

USER 33:33
WORKDIR /var/www/html