services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_MEMORY_LIMIT', '256M');
        define('WP_MAX_MEMORY_LIMIT', '256M');
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}

    volumes:
      - wp_content:/var/www/html/wp-content

    labels:
      - traefik.enable=true
      - traefik.http.routers.${SERVICE_NAME}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure
      - traefik.http.routers.${SERVICE_NAME}.tls=true
      - traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=80

  wpcli:
    build:
      context: .
      dockerfile: Dockerfile.wpcli

    user: "33:33"
    working_dir: /var/www/html
    command: ["sh", "-c", "sleep infinity"]
    restart: unless-stopped

    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      HOME: /tmp
      DOMAIN: ${DOMAIN}
      WP_TITLE: ${WP_TITLE}
      STUDENT_CODE: ${STUDENT_CODE}
      STUDENT_NAME: ${STUDENT_NAME}
      STUDENT_SURNAME: ${STUDENT_SURNAME}
      STUDENT_EMAIL: ${STUDENT_EMAIL}
      SUPPORT_USER: ${SUPPORT_USER}
      SUPPORT_EMAIL: ${SUPPORT_EMAIL}
      SUPPORT_PASSWORD: ${SUPPORT_PASSWORD}
      ELEMENTOR_PRO_LICENSE: ${ELEMENTOR_PRO_LICENSE}
    volumes:
      - wp_content:/var/www/html/wp-content

volumes:
  wp_content: